package com.demo.entities;
// Generated Mar 1, 2024, 2:08:08 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * AccountProuductId generated by hbm2java
 */
@Embeddable
public class AccountProuductId implements java.io.Serializable {

	private int accountId;
	private int productId;

	public AccountProuductId() {
	}

	public AccountProuductId(int accountId, int productId) {
		this.accountId = accountId;
		this.productId = productId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountProuductId))
			return false;
		AccountProuductId castOther = (AccountProuductId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
