package com.demo.entities;

import jakarta.persistence.*;

// Generated Mar 1, 2024, 2:08:08 PM by Hibernate Tools 4.3.6.Final


/**
 * AccountProuduct generated by hbm2java
 */
@Entity
@Table(name = "account_prouduct", catalog = "warehousemanagement")
public class AccountProuduct implements java.io.Serializable {

	private AccountProuductId id;
	private Account account;
	private Product product;

	public AccountProuduct() {
	}

	public AccountProuduct(AccountProuductId id, Account account, Product product) {
		this.id = id;
		this.account = account;
		this.product = product;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
	public AccountProuductId getId() {
		return this.id;
	}

	public void setId(AccountProuductId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
