package com.demo.entities;
// Generated Mar 1, 2024, 2:08:08 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import jakarta.persistence.*;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill", catalog = "warehousemanagement")
public class Bill implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Categorybill categorybill;
	private Date created;
	private String status;
	private double total;

	public Bill() {
	}

	public Bill(Account account, Categorybill categorybill, Date created, String status, double total) {
		this.account = account;
		this.categorybill = categorybill;
		this.created = created;
		this.status = status;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cate_bill_id", nullable = false)
	public Categorybill getCategorybill() {
		return this.categorybill;
	}

	public void setCategorybill(Categorybill categorybill) {
		this.categorybill = categorybill;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false, length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

}
