package com.demo.entities;
// Generated Mar 1, 2024, 2:08:08 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;
/**
 * Categorybill generated by hbm2java
 */
@Entity
@Table(name = "categorybill", catalog = "warehousemanagement")
public class Categorybill implements java.io.Serializable {

	private Integer id;
	private int name;
	private Set<Bill> bills = new HashSet<Bill>(0);

	public Categorybill() {
	}

	public Categorybill(int name) {
		this.name = name;
	}

	public Categorybill(int name, Set<Bill> bills) {
		this.name = name;
		this.bills = bills;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorybill")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
