package com.demo.entities;
// Generated Mar 1, 2024, 2:08:08 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "warehousemanagement")
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private int parent;
	private Set<Product> products = new HashSet<Product>(0);

	public Category() {
	}

	public Category(String name, int parent) {
		this.name = name;
		this.parent = parent;
	}

	public Category(String name, int parent, Set<Product> products) {
		this.name = name;
		this.parent = parent;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "parent", nullable = false)
	public int getParent() {
		return this.parent;
	}

	public void setParent(int parent) {
		this.parent = parent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
