package com.demo.entities;
// Generated Mar 1, 2024, 2:08:08 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "warehousemanagement")
public class Customer implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String phone;
	private String information;
	private Date created;
	private Set<InfoBill> infoBills = new HashSet<InfoBill>(0);

	public Customer() {
	}

	public Customer(String name, String address, String phone, String information, Date created) {
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.information = information;
		this.created = created;
	}

	public Customer(String name, String address, String phone, String information, Date created,
			Set<InfoBill> infoBills) {
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.information = information;
		this.created = created;
		this.infoBills = infoBills;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false, length = 250)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "information", nullable = false, length = 250)
	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<InfoBill> getInfoBills() {
		return this.infoBills;
	}

	public void setInfoBills(Set<InfoBill> infoBills) {
		this.infoBills = infoBills;
	}

}
