package com.demo.entities;

import jakarta.persistence.*;

// Generated Mar 1, 2024, 2:08:08 PM by Hibernate Tools 4.3.6.Final


/**
 * InfoBill generated by hbm2java
 */
@Entity
@Table(name = "info_bill", catalog = "warehousemanagement")
public class InfoBill implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private Product product;
	private int quantity;
	private int address;
	private int phone;

	public InfoBill() {
	}

	public InfoBill(Customer customer, Product product, int quantity, int address, int phone) {
		this.customer = customer;
		this.product = product;
		this.quantity = quantity;
		this.address = address;
		this.phone = phone;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "address", nullable = false)
	public int getAddress() {
		return this.address;
	}

	public void setAddress(int address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false)
	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

}
