package com.demo.entities;

import jakarta.persistence.*;

// Generated Mar 1, 2024, 2:08:08 PM by Hibernate Tools 4.3.6.Final



/**
 * InfoPicture generated by hbm2java
 */
@Entity
@Table(name = "info_picture", catalog = "warehousemanagement")
public class InfoPicture implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String name;

	public InfoPicture() {
	}

	public InfoPicture(Product product, String name) {
		this.product = product;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
